### ISSUE TITLE
Crash at the end of SFX loading when custom sounds exist

### ISSUE THREAD

**Issue by Kamayana** [chrislo27/RhythmHeavenRemixEditor#278]
### Information
**Log file**: [log_2019-03-17_16-08-05.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2975711/log_2019-03-17_16-08-05.txt)

**Editor version**: v3.17.1

### Description
The RHRE editor crashes whenever there is a custom sound inside of /.rhre3/customSounds, even on a fresh install. It doesn't matter if the custom sound is a vanilla override or an addition. This did not happen before v3.17.0. I have not tested if this still happens on a Windows PC.

### Behaviours
**Expected behaviour**: The game loads as normal, with custom sounds either overriding or adding to their respective games.

**Actual behaviour**: The game crashes at the very end of loading, while the Wizard Waltz icon is displayed, with "java.lang.IllegalStateException: parent.list() must not be null"

## Steps to reproduce issue
1. Open up a fresh install of RHRE v3.17.0+.
2. Run the program, and everything starts as expected.
3. Close RHRE and run RSDE v1.0.7.
4. Copy and Edit Existing Game Definition, and copy any of the games, doesn't matter what, and don't adjust anything.
5. Close RSDE and open RHRE again.
6. Crashes at the end of loading.

**Comment by chrislo27** [comment]
Cannot confirm on Windows 10 with RHRE v3.17.1 and RSDE v1.0.7. Please check that the `.rhre3/` folder and all of its subdirectories have read permissions.

However, I have released a reuploaded version to [v3.17.1](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/tag/v3.17.1) with a possible fix. Please try that as well.

**Comment by Kamayana** [comment]
The new v3.17.1 no longer crashes. Going by the log, it's still failing to list the files even with re-checked permissions, but my custom sounds seem to be loading perfectly fine anyway so as far as I can tell everything's in working order now.

Also, I tested it in my Windows partition and didn't have any problems, so it might be a Mac-specific issue, or even just specific to my PC.

Here's the log of the new version: [log_2019-03-17_18-31-50.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2975869/log_2019-03-17_18-31-50.txt)

**Comment by chrislo27** [comment]
Perhaps it might just be a volume partition issue. It's possible for the method I use to check case sensitivity on files to fail due to an I/O error -- specifically I think it could be that the volume formatting method doesn't support listing files, for whatever reason.

Anyway, glad to know the hotfix worked out. Thank you for having a well-formatted issue!
